networks:
  mktxp:
    driver: bridge

volumes:
  mktxp-logs:
    driver_opts:
       o: bind
       type: none
       device: /home/pi/Docker - Monitoring/mktxp-stack/syslog-ng/logs
  prometheus_storage: {}
  grafana_storage: {}

services:
  mktxp:
    container_name: mktxp
    image: ghcr.io/akpw/mktxp:latest
    user: root
    volumes:
      - './mktxp/:/root/mktxp/'
      - './syslog-ng/logs:/var/log/mktxp'
    networks:
      - mktxp
    depends_on:
      - syslog-ng
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        # Try this: https://daniel.es/blog/centralize-and-visualize-docker-logs-in-grafana-with-loki/
        # or this: https://abhiraj2001.medium.com/monitoring-docker-containers-with-grafana-loki-and-promtail-4302a9417c0d 

  grafana:
    container_name: grafana
    
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "WhiteTower2451!@"  # does not take effect if grafana db already exists
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "SonTech"   # Must match your org name
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_USERS_DEFAULT_THEME: "light"
      #GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/mikrotik/mikrotik_mktxp_exporter.json
      disableDeletion: "false"
      updateIntervalSeconds: 10
    image: grafana/grafana:latest
    networks:
      - mktxp
    ports:
    - protocol: tcp
      published: 80
      target: 3000
    restart: unless-stopped
    volumes:
    -  grafana_storage:/var/lib/grafana
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro

  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:latest
    networks:
      - mktxp
    ports:
    - protocol: tcp
      published: 3100
      target: 3100
    restart: unless-stopped
    volumes:
    - ./loki/loki-config.yml:/etc/loki/loki-config.yml

  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=1y
    - --web.enable-admin-api
    - --web.enable-lifecycle
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - mktxp
    ports:
    - published: 9090
      target: 9090
    restart: unless-stopped
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_storage:/prometheus
      # Target files directory
    - ./prometheus/targets:/etc/prometheus/targets:ro

  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:latest
    networks:
      - mktxp
    ports:
    - protocol: tcp
      published: 1514
      target: 1514
    - protocol: tcp
      published: 9080
      target: 9080
    restart: unless-stopped
    volumes:
    - ./promtail/promtail-config-fs.yml:/etc/promtail/promtail-config.yml:ro
    - mktxp-logs:/var/log:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro

  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    networks:
      - mktxp
    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: unless-stopped
    volumes:
    - ./syslog-ng/syslog-ng-fs.conf:/etc/syslog-ng/syslog-ng.conf:ro
    - mktxp-logs:/var/log/syslog-ng


  snmp-exporter:
    container_name: snmp-exporter
    image: quay.io/prometheus/snmp-exporter:latest
    ports:
      - "9116:9116"
      - "161:161/udp"
    volumes:
      - ./snmp-exporter:/etc/snmp-exporter
    command: --config.file=/etc/snmp-exporter/snmpGenerated.yml
    restart: unless-stopped
    networks:
      - mktxp


  ssid-change-detector:
      container_name: ssid-change-detector
      build:
        context: ./ssid-detector
        dockerfile: Dockerfile
      environment:
        - PROMETHEUS_URL=http://prometheus:9090
        - CHECK_INTERVAL=90  # in seconds
        - LOOKBACK_INTERVAL=90 # In seconds
      volumes:
        - ./ssid-detector/data:/data
      networks:
        - mktxp
      extra_hosts:
        - "host.docker.internal:host-gateway"
      restart: unless-stopped
      depends_on:
        - prometheus
        - loki
      logging:
        driver: loki
        options:
          loki-url: "http://localhost:3100/loki/api/v1/push"