{
 "title": "Nemo Dashboard",
 "tags": [ "overview" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "AP_Instances",
    "query": {
     "query": "query_result(ubntRadioMode != 1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Device Status",
   "type": "bargauge",
   "description": "All scraped jobs irrelevant to label or Role status.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up)", "legendFormat": "Total Scraped Devices" },
    { "expr": "sum(up)", "legendFormat": "Total UP" },
    { "expr": "count(up)-sum(up)", "legendFormat": "Total Down" }
   ]
  },
  {
   "title": "Active Devices Offline",
   "type": "table",
   "description": "Determines Devices that are failing to scrape by Prometheous.\nActive Device as defined by manual label \"role\"",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "count by (instance) (last_over_time(up{role!=\"ColdSpares\", role!=\"Cancelled-unrecovered\", role!=\"Infrastructure-Maintenance\"}[5m]) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devices with Critical or Warning Logs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"syslog\"} [$__interval] |~ \"(?i)critical|warning\")",
     "legendFormat": "{{routerboard}}"
    }
   ]
  },
  {
   "title": "List of APs With Airtimes Exceeding 85% in the last 72 hours",
   "type": "table",
   "description": "Time Resolution is in 5 min increments",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum_over_time(\r\n  (\r\n    (sum by (instance)((ubntStaTxAirtime{instance=~\"$AP_Instances\"} + ubntStaRxAirtime{instance=~\"$AP_Instances\"}) / 10) > 85)\r\n    /\r\n    (sum by (instance)((ubntStaTxAirtime{instance=~\"$AP_Instances\"} + ubntStaRxAirtime{instance=~\"$AP_Instances\"}) / 10) > 85)\r\n  )[72h:5m]\r\n)*5\r\n#mulitply by 5 (same as interval) to convert from count to minutes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSID Changes",
   "type": "table",
   "description": "Used to determine if station has moved to secondary. Only looks for changes as secondary SSID value is not accessible currently.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=\"ssid-change-detector\"} \r\n| json \r\n| event=\"ssid_change\""
    }
   ]
  },
  {
   "title": "Primary Nodes Throughput and Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "WAN Traffic",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mktxp_interface_rx_byte_total{routerboard_name=\"Nemo Primary\", name=\"ether1-WAN1\"}[4m])*8",
     "legendFormat": "In | {{routerboard_name}} - {{name}}"
    },
    {
     "expr": " rate(mktxp_interface_tx_byte_total{routerboard_name=\"Nemo Primary\", name=\"ether1-WAN1\"}[4m])*8",
     "legendFormat": "Out| {{routerboard_name}} - {{name}}"
    },
    {
     "expr": " rate(mktxp_interface_rx_byte_total{routerboard_name=\"Nemo Primary\", name=\"ether2-WAN2\"}[4m])*8",
     "legendFormat": "In | {{routerboard_name}} - {{name}}"
    },
    {
     "expr": " rate(mktxp_interface_tx_byte_total{routerboard_name=\"Nemo Primary\", name=\"ether2-WAN2\"}[4m])*8",
     "legendFormat": "Out | {{routerboard_name}} - {{name}}"
    },
    {
     "expr": "rate(mktxp_interface_rx_byte_total{routerboard_name=\"Nemo Backup\", name=\"ether1-WAN1\"}[4m])*8",
     "legendFormat": "In | {{routerboard_name}} - {{name}}"
    },
    {
     "expr": "rate(mktxp_interface_tx_byte_total{routerboard_name=\"Nemo Backup\", name=\"ether1-WAN1\"}[4m])*8",
     "legendFormat": "Out | {{routerboard_name}} - {{name}}"
    },
    {
     "expr": "rate(mktxp_interface_rx_byte_total{routerboard_name=\"Nemo Backup\", name=\"ether2-WAN2\"}[4m])*8",
     "legendFormat": "In | {{routerboard_name}} - {{name}}"
    },
    {
     "expr": "rate(mktxp_interface_rx_byte_total{routerboard_name=\"Nemo Backup\", name=\"ether2-WAN2\"}[4m])*8",
     "legendFormat": "Out | {{routerboard_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "Sass Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mktxp_interface_rx_byte_total{name=~\"(?i).*sass.*\", name!~\".*AP.*\"}[4m])*8",
     "legendFormat": "In | {{routerboard_name}} - {{name}}"
    },
    {
     "expr": "rate(mktxp_interface_tx_byte_total{name=~\"(?i).*sass.*\", name!~\".*AP.*\"}[4m])*8",
     "legendFormat": "Out | {{routerboard_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "Sass Secondary Station Total AirTime as Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (ubntStaRxAirtime{instance=\"10.10.10.57\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total RX - {{sysName}}"
    },
    {
     "expr": "sum by(instance) (ubntStaTxAirtime{instance=\"10.10.10.57\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total TX - {{sysName}}"
    },
    {
     "expr": "sum by(instance) (ubntStaRxAirtime{instance=\"10.10.10.57\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)\r\n\r\n+ \r\n\r\nsum by(instance) (ubntStaTxAirtime{instance=\"10.10.10.57\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total - {{sysName}}"
    }
   ]
  },
  {
   "title": "Water Tower Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mktxp_interface_rx_byte_total{name=~\"(?i).*WT.*\", name!~\".*AP.*\"}[4m])*8",
     "legendFormat": "In | {{routerboard_name}} - {{name}}"
    },
    {
     "expr": "rate(mktxp_interface_tx_byte_total{name=~\"(?i).*WT.*\", name!~\".*AP.*\"}[4m])*8",
     "legendFormat": "Out | {{routerboard_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "Water Tower Station Total AirTime as Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (ubntStaRxAirtime{instance=\"10.10.10.59\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total RX - {{sysName}}"
    },
    {
     "expr": "sum by(instance) (ubntStaTxAirtime{instance=\"10.10.10.59\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total TX - {{sysName}}"
    },
    {
     "expr": "sum by(instance) (ubntStaRxAirtime{instance=\"10.10.10.59\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)\r\n\r\n+ \r\n\r\nsum by(instance) (ubntStaTxAirtime{instance=\"10.10.10.59\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total - {{sysName}}"
    }
   ]
  },
  {
   "title": "Morford Station Tower Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifInOctets{instance=\"10.10.10.69\", ifDescr=\"eth0\"}[3m]) * 8\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "In |  {{ifDescr}} - {{sysName}}"
    },
    {
     "expr": "rate(ifOutOctets{instance=\"10.10.10.69\", ifDescr=\"eth0\"}[3m]) * 8\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Out | {{ifDescr}} - {{sysName}}"
    }
   ]
  },
  {
   "title": "Morford Station Total AirTime as Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (ubntStaRxAirtime{instance=\"10.10.10.69\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total RX - {{sysName}}"
    },
    {
     "expr": "sum by(instance) (ubntStaTxAirtime{instance=\"10.10.10.69\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total TX - {{sysName}}"
    },
    {
     "expr": "sum by(instance) (ubntStaRxAirtime{instance=\"10.10.10.69\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)\r\n\r\n+ \r\n\r\nsum by(instance) (ubntStaTxAirtime{instance=\"10.10.10.69\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total - {{sysName}}"
    }
   ]
  },
  {
   "title": "Park Shed Station Tower Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifInOctets{instance=\"10.10.10.47\", ifDescr=\"eth0\"}[3m]) * 8\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "In |  {{ifDescr}} - {{sysName}}"
    },
    {
     "expr": "rate(ifOutOctets{instance=\"10.10.10.47\", ifDescr=\"eth0\"}[3m]) * 8\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Out | {{ifDescr}} - {{sysName}}"
    }
   ]
  },
  {
   "title": "Park Shed Station Total AirTime as Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (ubntStaRxAirtime{instance=\"10.10.10.47\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total RX - {{sysName}}"
    },
    {
     "expr": "sum by(instance) (ubntStaTxAirtime{instance=\"10.10.10.47\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total TX - {{sysName}}"
    },
    {
     "expr": "sum by(instance) (ubntStaRxAirtime{instance=\"10.10.10.47\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)\r\n\r\n+ \r\n\r\nsum by(instance) (ubntStaTxAirtime{instance=\"10.10.10.47\"}) / 10\r\n* on(instance) group_left(sysName) \r\n(max by(instance, sysName) (sysName) * 0 + 1)",
     "legendFormat": "Total - {{sysName}}"
    }
   ]
  }
 ]
}