{
 "title": "Ubiquiti SW and UPS",
 "description": "Intended for information for UISP-S and UISP-P",
 "tags": [ "drilldown" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": "query_result(sum by (job)(ifInOctets{}))"
   },
   {
    "name": "Device",
    "query": "query_result(sum by (instance)(ifInOctets{job=\"$Job\"}))"
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(ifInOctets{instance=\"$Device\"},ifAlias)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Intefaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysName{job=\"$Job\", instance=\"$Device\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Switch management uptime",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"$Job\",instance=\"$Device\"} /100"
    }
   ]
  },
  {
   "title": "Errors Detected",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifOutErrors{job=\"$Job\",instance=\"$Device\"}[5m]) + irate(ifInErrors{job=\"$Job\",instance=\"$Device\"}[5m])",
     "legendFormat": "{{ifAlias}} Errors"
    },
    {
     "expr": "irate(ifOutDiscards{job=\"$Job\",instance=\"$Device\"}[5m]) + irate(ifInDiscards{job=\"$Job\",instance=\"$Device\"}[5m])",
     "legendFormat": "{{ifAlias}} Discards"
    }
   ]
  },
  {
   "title": "Ports Up",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ifOperStatus{job=\"$Job\",instance=\"$Device\"} == 1)",
     "legendFormat": "Connected"
    }
   ]
  },
  {
   "title": "Throughput $interface",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ifOutOctets{job=\"$Job\",instance=\"$Device\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Out | {{ifAlias}}"
    },
    {
     "expr": "irate(ifInOctets{job=\"$Job\",instance=\"$Device\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "In | {{ifAlias}}"
    }
   ]
  },
  {
   "title": "Ethernet Ports: Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifConnectorPresent{instance=\"$Device\", ifIndex!~\".*100.*\"}",
     "legendFormat": "{{ifAlias}} 0/{{ifIndex}} "
    }
   ]
  },
  {
   "title": "Ethernet Ports: Full Duplex",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$Device\", ifIndex!~\".*100.*\"}",
     "legendFormat": "{{ifAlias}} {{ifIndex}}"
    }
   ]
  },
  {
   "title": "Ethernet Ports: Last Change",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifLastChange{instance=\"$Device\", ifIndex!~\".*100.*\"}",
     "legendFormat": "{{ifAlias}} 0/{{ifIndex}} "
    }
   ]
  },
  { "title": "Ubiquiti UISP Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Output Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "ubntPowerOutCurrent{instance=\"$Device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ubntPowerOutVoltage{instance=\"$Device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "ubntPowerOutPower{instance=\"$Device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSU Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntPsuStatus{instance=\"$Device\"}",
     "legendFormat": "{{ubntPsuIndex}}"
    }
   ]
  },
  {
   "title": "PSU Charging",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntPsuCharging{instance=\"$Device\"}",
     "legendFormat": "{{ubntPsuIndex}}"
    }
   ]
  },
  {
   "title": "PSU Type",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntPsuType{instance=\"$Device\"}",
     "legendFormat": "{{ubntPsuIndex}}"
    }
   ]
  },
  {
   "title": "PSU Charge Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ubntPsuBatteryChargeLevel{instance=\"$Device\"}",
     "legendFormat": "{{ubntPsuIndex}}"
    }
   ]
  },
  {
   "title": "PSU Battery Time Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ubntPsuBatteryTimeRemaining{instance=\"$Device\"}",
     "legendFormat": "{{ubntPsuIndex}}"
    }
   ]
  },
  {
   "title": "PSU Operational Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "ubntPsuOperStatus{instance=\"$Device\"}",
     "legendFormat": "{{ubntPsuIndex}}"
    }
   ]
  }
 ]
}